default: &default
  adapter: mysql2
  encoding: utf8
  host: localhost
  pool: 5
  username: root
  password: 123456
  # socket: /var/lib/mysql/mysql.sock
  # socket: /tmp/mysql.sock
development:
  <<: *default
  database: captk

production:
  <<: *default
  database: captk_pro
  # username: my_app
  # password: <%= ENV['MY_APP_DATABASE_PASSWORD'] %>

test:
  <<: *default
  database: captk_test

# server "47.93.29.146:55569"